title: Harshal Bhakta
description: Harshal Bhakta
author: Harshal Bhakta
github: https://github.com/harshalbhakta
about: I am the co-founder of TeachMore.
disqus_shortname: harshalbhakta
google_analytics: UA-48806472-1
avatar_url: /static/img/harshal-profile.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/harshal.bhakta"
    - icon: fa-twitter
      link: "https://twitter.com/harsha_bhakta"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/harshal-bhakta-55681216/"
    - icon: fa-stack-exchange
      link: "https://stackexchange.com/users/1733229/harshal-bhakta"
    - icon: fa-github
      link: "https://github.com/harshalbhakta"

share:
  twitter_username: harshalbhakta
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Articles
      url: /articles/
    - text: Books
      url: /books/
    - text: Decks
      url: /decks/
    - text: Tools
      url: /tools/

url: "https://harshalbhakta.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
